caelun-ruby-on-rais/restaurante/config/routes.rb
Rails.application.routes.draw do
  resources :qualificacoes

  resources :clientes

  resources :comentarios

  get 'restaurantes/index'
  get 'restaurantes/new'
  get 'restaurantes/show'

  get 'restaurantes/destroy'

  get 'restaurantes/create'  
  post 'restaurantes/create'

  get 'restaurantes/edit'
  post 'restaurantes/update'

  get 'greetings/hello'

  get 'hello_world/hello'

  get 'hello_world/index'

end

caelun-ruby-on-rais/restaurante/app/models/qualificacoes.rb
class Qualificacoes < ActiveRecord::Base


	belongs_to :cliente

	belongs_to :restaurantes

	validates_presence_of :nota, :message => " - deve ser preenchido"

	validates_presence_of :cliente_id, :restaurante_id

	validates_presence_of :valor_gasto, :message => " - deve ser preenchido"

	validades_numericality_of :nota,
								:greater_than_or_equal_to => 0
								:less_than_or_equal_to => 10,
								:message => " - deve ser um número entre 0 e 10"	

	validades_numericality_of :valor_gasto,
								:greater_than => 0
								
								:message => " - deve ser um número maior que 0"							

	validates_associated :cliente_id, :restaurante_id

end

caelun-ruby-on-rais/restaurante/app/controllers/qualificacoes_controller.rb
class QualificacoesController < ApplicationController
  before_action :set_qualificacao, only: [:show, :edit, :update, :destroy]

  # GET /qualificacoes
  # GET /qualificacoes.json
  def index
    @qualificacoes = Qualificacao.all
  end

  # GET /qualificacoes/1
  # GET /qualificacoes/1.json
  def show
  end

  # GET /qualificacoes/new
  def new
    @qualificacao = Qualificacao.new
  end

  # GET /qualificacoes/1/edit
  def edit
  end

  # POST /qualificacoes
  # POST /qualificacoes.json
  def create
    @qualificacao = Qualificacao.new(qualificacao_params)

    respond_to do |format|
      if @qualificacao.save
        format.html { redirect_to @qualificacao, notice: 'Qualificacao was successfully created.' }
        format.json { render :show, status: :created, location: @qualificacao }
      else
        format.html { render :new }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qualificacoes/1
  # PATCH/PUT /qualificacoes/1.json
  def update
    respond_to do |format|
      if @qualificacao.update(qualificacao_params)
        format.html { redirect_to @qualificacao, notice: 'Qualificacao was successfully updated.' }
        format.json { render :show, status: :ok, location: @qualificacao }
      else
        format.html { render :edit }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualificacoes/1
  # DELETE /qualificacoes/1.json
  def destroy
    @qualificacao.destroy
    respond_to do |format|
      format.html { redirect_to qualificacoes_url, notice: 'Qualificacao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qualificacao
      @qualificacao = Qualificacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qualificacao_params
      params[:qualificacao]
    end
end

caelun-ruby-on-rais/restaurante/app/helpers/qualificacoes_helper.rb
module QualificacoesHelper
end

caelun-ruby-on-rais/restaurante/app/views/qualificacoes/_form.html.erb
<%= form_for(@qualificacao) do |f| %>
  <% if @qualificacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qualificacao.errors.count, "error") %> prohibited this qualificacao from being saved:</h2>

      <ul>
      <% @qualificacao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

caelun-ruby-on-rais/restaurante/app/views/qualificacoes/edit.html.erb
<h1>Editing qualificacao</h1>

<%= render 'form' %>

<%= link_to 'Show', @qualificacao %> |
<%= link_to 'Back', qualificacoes_path %>

caelun-ruby-on-rais/restaurante/app/views/qualificacoes/index.html.erb
<h1>Listing qualificacoes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qualificacoes.each do |qualificacao| %>
      <tr>
        <td><%= link_to 'Show', qualificacao %></td>
        <td><%= link_to 'Edit', edit_qualificacao_path(qualificacao) %></td>
        <td><%= link_to 'Destroy', qualificacao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qualificacao', new_qualificacao_path %>

caelun-ruby-on-rais/restaurante/app/views/qualificacoes/new.html.erb
<h1>New qualificacao</h1>

<%= render 'form' %>

<%= link_to 'Back', qualificacoes_path %>

caelun-ruby-on-rais/restaurante/app/views/qualificacoes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_qualificacao_path(@qualificacao) %> |
<%= link_to 'Back', qualificacoes_path %>